---

- name: WebServer Setup
  hosts: webservers
  become: yes
  tasks:

  - name: Install Httpd
    yum:
      name: httpd
      state: present

  - name: Enable and Start Httpd Service
    systemd:
      name: httpd
      state: started
      enabled: yes
  - name: Copy Index.html file
    copy:
      src: index.html
      dest: /var/www/html/index.html
      backup: yes
